version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    build: .
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5000:5000"
    depends_on:
      - db

secrets:
  postgres_password:
    file: ./secrets/postgres_password
